release/example/crk.wordlist_wahkohtowin/example.crk.wordlist_wahkohtowin.model_info, release/example/crk.wordlist_wahkohtowin/source/cree-kinship.tsv, release/example/crk.wordlist_wahkohtowin/source/example.crk.wordlist_wahkohtowin.model.kps, release/example/crk.wordlist_wahkohtowin/source/model.ts
This is an example wordlist that I exported from [Google Sheets](https://docs.google.com/spreadsheets/d/1-3G9RQGN9HPT35_-7T9_6G1zbHGcVPbJP9GhmIh0EHI/edit?usp=sharing). I exported as a TSV, which will work with the compiler implemented in #7.
I wanted to determine the workflow of having my wordlist in a spreadsheet, exporting it, and adding it to the public list of lexical models. This is the result!
=> Add basic Cree example, exported from Google Sheets

tools/build-trie.ts, tools/index.ts
This PR implements a simple little TSV parser, and generates a data structure suitable for the initialization of the wordlist model. We call it the "trie" model, but the PR **does not construct a trie**. That's for the future, but this should work with the current version of the wordlist model.
Essentially, this takes a wordlist with the following contents:
```tsv
armadillo	10	Small armoured mammal
bat	15	Small flying mammal
buffalo	6	Large non-flying mammal
cat	25	Small cheetah
cheetah	7	Large cat
dinosaur	11	Large non-flying non-mammal
dumbo octopus	1	Cute aquatic non-mammal
octopusses	9	THE ONLY RIGHT WAY
```
And compiles it to the following code (pretty-printed):
```js
(function () {
'use strict';
var model = {};
model.backingData = [
["armadillo", 10],
["bat", 15],
["buffalo", 6], …
```
=> Compile 'trie' data structure

release/example/crk.wordlist_wahkohtowin/source/example.crk.wordlist_wahkohtowin.model.kps
Fix the typo in the model ID which was preventing the mobile apps from installing the model.
=> Fix ID to crk.wordlist_wahkohtowin

release/example/crk.wordlist_wahkohtowin/source/example.crk.wordlist_wahkohtowin.model.kps, release/example/en.custom/source/example.en.custom.model.kps, release/example/en.wordlist/source/example.en.wordlist.model.kps, tools/kmp-compiler.ts
Fixes #15.
The .kps entries for readme.htm were removed so that they didn't break .kmp compilation; the corresponding files do not yet exist in our examples.
=> Fixes .kmp bundling.

release/example/en.custom/source/example.en.custom.model.kps, tools/index.ts
During the compilation rework, I accidentally left in code that added an extraneous `com.keyman.lexicalModel.register();` statement to custom models.  This broke the LMLayerWorker when attempting to load said model.
=> Removes breaking statement from custom models

tools/build-trie.ts
Small patch that fixes a bug when a TSV file is simply a list of words with no counts -- this is valid according to the spec we laid out. Here's an example of the crash:
```
Building lexical models for release
- Building release/example
Validating model /Users/santoseadmin/Work/lexical-models/release/example/crk.wordlist_general/
Building model /Users/santoseadmin/Work/lexical-models/release/example/crk.wordlist_general/
/Users/santoseadmin/Work/lexical-models/release/example/crk.wordlist_general/build/obj/tools/build-trie.js:43
countText = countText.trim();
^
TypeError: Cannot read property 'trim' of undefined
at Object.createTrieDataStructure (/Users/santoseadmin/Work/lexical-models/release/example/crk.wordlist_general/build/obj/tools/build-trie.js:43:31)
at LexicalModelCompiler.compile …
```
=> Fix crash when TSV does not provide a count

release/example/en.wordlist/source/example.en.wordlist.model.kps, release/example/en.wordlist/source/model.ts, tools/index.ts, tools/lexical-model.ts
This generates model code compatible with keymanapp/keyman#1755. The main idea here is that the `model.ts` can specify a string for `wordBreaking`, e.g., 
```ts
(new LexicalModelCompiler).compile({
format: 'trie-1.0',
wordBreaking: 'ascii',
sources: ['example.tsv']
});
```
And the compiler will generate the code to instantiate the model.
`example.en.wordlist` has been changed to use this feature and compile with a "built-in" word breaker.
**NOTE**: I strongly suggest tidying up `index.ts` once this PR is merged before adding any more features.
=> Implement new-style word breaking

release/example/en.custom/example.en.custom.model_info, release/example/en.custom/source/example.en.custom.model.kps
Currently, the embedded apps don't have the ability to selectively install/uninstall lexical models.
When a keyboard is installed, the first associated lexical model gets added.
In order to use the preferred "en.wordlist" model, we're temporarily assigning "en.custom" to German (de)
=> Temporarily assign "de" to en.custom.model

release/example/str.trie_sencoten/source/example.str.trie_sencoten.model.kps
I was having issues on the mobile app installing example.str.trie_sencoten.model.kmp.
The model filename is `example.str.trie_sencoten.model.js`
so the lexical model ID `example.str.trie` is missing the `_sencoten` portion.
Note, the model will still be unavailable from api.keyman.com because of issue keymanapp/keyman#1793
=> [str.trie_sencoten] Fix the model ID

release/example/str.trie_sencoten/source/example.str.trie_sencoten.model.kps
OK, now that keymanapp/keyman#1798 is merged, this *should* make the model available from the Keyman cloud
=> [str.trie_sencoten] Bump model version again

release/example/str.trie_sencoten/source/model.ts
This adds a key function that nullfies the difference between uppercase and
lowercase letters, and whether accents matter when typing SENĆOŦEN.
=> [example.str.trie_sencoten] Implement key function for SENĆOŦEN.

release/example/str.trie_sencoten/source/example.str.trie_sencoten.model.kps, release/example/str.trie_sencoten/source/model.ts
Depends on keymanapp/keyman#1805 being merged. Since trie-1.0 and trie-2.0 are
identical now, this changes the only model that uses it to use trie-1.0
instead.
=> Use trie-1.0 everywhere

release/example/crk.wordlist_wahkohtowin/source/example.crk.wordlist_wahkohtowin.model.kps, release/example/en.custom/source/example.en.custom.model.kps, release/example/en.mtnt/source/example.en.mtnt.model.kps, release/example/en.wordlist/source/example.en.wordlist.model.kps, release/nrc/str.sencoten/source/nrc.str.sencoten.model.kps
The existing lexical models have long names that are difficult to display in the "dictionary selection" screen on the mobile apps. Hence, I've shortened the names for many of these, and removed the word "model" or "lexical model" in names, opting for "dictionary" instead.
I have also bumped version numbers for all models. Note: I have not modified example.str.trie_senchoten because it is completely obsoleted by the nrc.str.sencoten.
=> Simplify existing models' names.

ci.sh
Fixes errors in CI with duplicated shortnames, e.g. 
```
[Step 3/5] Failed to locate /c/BuildAgent/work/e22cfa4d1a6faf97/models/release/nrc/nrc.en.mtnt/build/nrc.nrc.en.mtnt.model_info
```
https://build.palaso.org/viewLog.html?buildId=161961&buildTypeId=Keyman_Models_BuildAndDeploy&tab=buildLog&_focus=742
=> [meta] Fixup ci.sh with new path formats (remove duplicated shortname)

release/nrc/nrc.en.mtnt/nrc.en.mtnt.kpj, release/nrc/nrc.str.sencoten/nrc.str.sencoten.kpj, sample/example/example.crk.wordlist_wahkohtowin/example.crk.wordlist_wahkohtowin.kpj, sample/example/example.en.custom/example.en.custom.kpj, sample/example/example.en.wordlist/example.en.wordlist.kpj
Since Developer can now edit TSV files (accessible from the "Models" tab),
this PR adds the .tsv wordlists to the project files so they'll be accessible in future maintenance.
I'm not incrementing any version numbers because the models aren't being updated.
(Some version info appear in the `example` projects, but that's from when Developer saves the projects)
=> Add .tsv files to project files

README.md, build.sh, package-lock.json, package.json, resources/compile.sh
Now that Keyman 12.0 is released, we can update this repo to use the npm dependencies.
@keymanapp/lexical-model-compiler
@keymanapp/lexical-model-types
I've modified `-no-npm` flag to skip all npm steps. 
For my personal testing of `-no-npm`, I uninstalled Developer and 
```
npm uninstall -g @keymanapp/lexical-model-compiler
```
=> Use lexical-model-compiler npm packages

release/nrc/nrc.str.sencoten/nrc.str.sencoten.kpj, release/nrc/nrc.str.sencoten/source/nrc.str.sencoten.model.kps
Earlier versions claimed the NRC held the copyright to the model data. This is incorrect; the wordlist is handled by Timothy Montler and the W̱SÁNEĆ School Board.
=> [nrc.str.sencoten] Correct copyright.

release/nrc/nrc.en.mtnt/HISTORY.md, release/nrc/nrc.en.mtnt/source/mtnt.tsv, release/nrc/nrc.en.mtnt/source/nrc.en.mtnt.model.kps
This is a mitigation for keymanapp/keyman#2374.
=> fix(nrc.en.mtnt): remove SMP characters

release/nrc/nrc.en.mtnt/HISTORY.md, release/nrc/nrc.en.mtnt/nrc.en.mtnt.kpj, release/nrc/nrc.en.mtnt/source/nrc.en.mtnt.model.kps, release/nrc/nrc.str.sencoten/HISTORY.md, release/nrc/nrc.str.sencoten/nrc.str.sencoten.kpj, release/nrc/nrc.str.sencoten/source/nrc.str.sencoten.model.kps, sample/example/example.crk.wordlist_wahkohtowin/source/example.crk.wordlist_wahkohtowin.model.kps, sample/example/example.en.custom/source/example.en.custom.model.kps, sample/example/example.en.wordlist/source/example.en.wordlist.model.kps, sample/example/example.ta.wordlist/source/example.ta.wordlist.model.kps
Fixes #62
We decided the package version is what gets used for lexical model version.
For compatibility when compiling lexical model projects in Keyman Developer:
* Remove `<FollowKeyboardVersion/>` in the .kps files
* Remove `<Version> </Version>` tags within the `<LexicalModel>` nodes
Also updated HISTORY.md files for the nrc models (The "latest" mtnt version is 0.1.3)
=> Fix versioning in kps files

release/sil/sil.glk-arab.ptwl1/HISTORY.md, release/sil/sil.glk-arab.ptwl1/README.md, release/sil/sil.glk-arab.ptwl1/source/sil.glk-arab.ptwl1.model.kps, release/sil/sil.glk-arab.ptwl1/source/sil.glk-arab.ptwl1.model.ts
=> [sil.glk-arab.ptwl1] Convert source from ANSI to UTF-8

release/sil/sil.bcc-latn.upp_ptwl1/source/sil.bcc-latn.upp_ptwl1.model.ts, release/wyc_eth/wyc_eth.mym-latn.me_en/source/wyc_eth.mym-latn.me_en.model.ts
This converts two more lexical models from ANSI to UTF-8 encoding.
I didn't bump the versions since it only involved comments.
* sil.bcc-latn.upp_ptwl1.model.ts
* wyc_eth.mym-latn.me_en.model.ts
=> Convert some model.ts from ANSI to UTF-8

package-lock.json, package.json, release/sapradhan/sapradhan.new-newa.nepal_bhasa/HISTORY.md, release/sapradhan/sapradhan.new-newa.nepal_bhasa/README.md, release/sapradhan/sapradhan.new-newa.nepal_bhasa/sapradhan.new-newa.nepal_bhasa.kpj, release/sapradhan/sapradhan.new-newa.nepal_bhasa/source/sapradhan.new-newa.nepal_bhasa.model.kps
Attempts to address #97
* Update lexical model compiler from 12.0.66 to 13.0.109 stable
* Update lexical-model-types from 12.0.100 to 13.0.107
* Bump newa version to trigger rebuild
=> Update compiler to 13.0.109, bump newa version

package-lock.json, package.json, release/sapradhan/sapradhan.new-newa.nepal_bhasa/HISTORY.md, release/sapradhan/sapradhan.new-newa.nepal_bhasa/README.md, release/sapradhan/sapradhan.new-newa.nepal_bhasa/sapradhan.new-newa.nepal_bhasa.kpj, release/sapradhan/sapradhan.new-newa.nepal_bhasa/source/sapradhan.new-newa.nepal_bhasa.model.kps
Fixes #97 
The Newa model uses SMP characters.
The current version of node in package.json `^11.15.0` generates an invalid Newa lexical-model (splits surrogate pairs).
Updating node to the latest LTS `14.15.0` fixes the compilation.
Also bumped the Newa model version to force a rebuild.
=> [newa] Update node version and rebuild Newa model

release/gff/gff.sgw.gurage/HISTORY.md, release/gff/gff.sgw.gurage/README.md, release/gff/gff.sgw.gurage/gff.sgw.gurage.kpj, release/gff/gff.sgw.gurage/source/gff.sgw.gurage.model.kps, release/gff/gff.sgw.gurage/source/readme.htm
The change of language identifier is made to synchronize with the identifier used in the GFF Gurage keyboard, and is discussed in the Keyman App Issue 3806 (https://github.com/keymanapp/keyman/issues/3806).
While this change is necessary, one issue does arise whereby this lexical model uses the provisional Gurage orthography applied by the GFF Gurage (gff_gurage) keyboard, but  **_not_** by the GFF Gurage Legacy (gff_gurage_legacy) keyboard.  However, both keyboards use the sgw-Ethi identifier.  
Is there any change that could be made to the respective identifiers such that this lexical model is **_only_** used by the gff_gurage keyboard?
=> SGW ⇒ SGW-ETHI

package-lock.json, package.json, release/nrc/nrc.en.mtnt/HISTORY.md, release/nrc/nrc.en.mtnt/LICENSE.md, release/nrc/nrc.en.mtnt/README.md, release/nrc/nrc.en.mtnt/nrc.en.mtnt.kpj, release/nrc/nrc.en.mtnt/source/nrc.en.mtnt.model.kps, release/nrc/nrc.en.mtnt/source/nrc.en.mtnt.model.ts
Fixes #108.
Fixes https://github.com/keymanapp/keyman/issues/4115.
Since we're introducing some new predictive-text features for version 14, we should _probably_ shift this repo to a version 14 compiler sooner rather than later, even if it is still in beta.  There were some obstacles for this (see the very-recent https://github.com/keymanapp/keyman/pull/4291 and https://github.com/keymanapp/keyman/pull/4299), but they're now cleared.
This also allows us to enable case-detection behavior for predictive text models on a case-by-case basis.  Since we push English / `sil_euro_latin` as the default language / keyboard pair, it's only natural that our first example of this be the default English model.
=> chore: model compiler update, fix: English (MTNT) model casing

build.sh, resources/compile.sh
Piggy-backing on #109 to get the compiler update
This fixes #55 in tidying up the build script to use `set -u`.
=> feat: Update build scripts to use `set -u`

package-lock.json, package.json, release/nrc/nrc.en.mtnt/HISTORY.md, release/nrc/nrc.en.mtnt/nrc.en.mtnt.kpj, release/nrc/nrc.en.mtnt/source/nrc.en.mtnt.model.kps
This PR is motivated by https://github.com/keymanapp/keyman/pull/4504.
In short, a compiler bug partially broke the MTNT model's weighting.
=> fix: updates compiler, MTNT due to de-duplication bug

package-lock.json, package.json, release/katelem/katelem.ann-latn.getat/HISTORY.md, release/katelem/katelem.ann-latn.getat/README.md, release/katelem/katelem.ann-latn.getat/katelem.ann-latn.getat.kpj, release/katelem/katelem.ann-latn.getat/source/katelem.ann-latn.getat.model.kps, release/katelem/katelem.ann-latn.getat/source/welcome.htm, release/nrc/nrc.en.mtnt/HISTORY.md, release/nrc/nrc.en.mtnt/nrc.en.mtnt.kpj, release/nrc/nrc.en.mtnt/source/nrc.en.mtnt.model.kps
Fixes #124.
I haven't updated copyright dates because the change is inconsequential and actually only a version increment to get the new version deployed.
=> fix: Update LM compiler version and support Android 5.0

package-lock.json, package.json
This updates the lexical model compiler which downgrades non-canonical BCP-47 tags to Info
=> chore: Update compiler to 14.0.272

release/fv/fv.bea.tsaadane/.gitignore, release/fv/fv.bea.tsaadane/README_EXTERNAL.md, release/fv/fv.bea.tsaadane/external_source, resources/compile.sh, resources/external.sh
Hi Keyman team!
Testing our process out with a model for Dane-Z̲aa Z̲áágéʔ, keyboard should be: https://keyman.com/keyboards/fv_dane_zaa_zaage
Hashes:
fv.bea.tsaadane.model.js
0ad792674ee8ff752aa9c353e88c1a4013b17bbb35636759fcca494d47886442  
fv.bea.tsaadane.model.kmp
2132bc5a1f137a48c3189654f7aa92bdee5ad352bc850c6986a51652fed1ea31  
fv.bea.tsaadane.model_info
aca69c5d168437cfaaa3c9b6fe85e36c1df71904a0ce971c357ae42292313be0
I wasn't sure what format to include these in the `release/fv/fv.bea.tsaadane/external_source` file.
=> [fv.bea.tsaadane] Initial commit for fv-bea-tsaadane

release/nrc/nrc.en.mtnt/HISTORY.md, release/nrc/nrc.en.mtnt/LICENSE.md, release/nrc/nrc.en.mtnt/README.md, release/nrc/nrc.en.mtnt/source/mtnt.tsv, release/nrc/nrc.en.mtnt/source/nrc.en.mtnt.model.kps
Addresses some of #143 in cleaning up the following from the en.mtnt wordlist:
* typos of contractions
* teh
* symbols:
* currencies
* emojis
* non-Latin characters
* full-width punctuation
Items not addressed on this PR:
* usage of left-single quotation marks for contractions in the wordlist
* British spelling
* slang
=> [en.mtnt] - Remove symbols and typos of contractions

package-lock.json, package.json
Accompanying the Keyman 16.0.138 release, this updates the lexical-model compiler from 15.0 to 16.0
There's a multititude of compiler warnings
* duplicate words found in a (wordlist) file; summing counts
* entries not being Unicode NFC. Automatically converting to NFC
But the overall build passes
I note node is still  `"^14.15.0",` which we should update to LTS at some point.
=> chore: Update lexical-model compiler to 16.0.138

release/dotland/dotland.ru.russian/HISTORY.md, release/dotland/dotland.ru.russian/source/dotland.ru.russian.model.kps, release/iles/iles.chp.indigenous_nt/HISTORY.md, release/iles/iles.chp.indigenous_nt/source/iles.chp.indigenous_nt.model.kps, release/iles/iles.dgr.indigenous_nt/HISTORY.md, release/iles/iles.dgr.indigenous_nt/source/iles.dgr.indigenous_nt.model.kps, release/nrc/nrc.str.sencoten/HISTORY.md, release/nrc/nrc.str.sencoten/source/nrc.str.sencoten.model.kps, release/sil/sil.bcc-arab.upp_ptwl1/HISTORY.md, release/sil/sil.bcc-arab.upp_ptwl1/source/sil.bcc-arab.upp_ptwl1.model.kps, release/sil/sil.glk-arab.ptwl1/HISTORY.md, release/sil/sil.glk-arab.ptwl1/source/sil.glk-arab.ptwl1.model.kps, release/sil/sil.kjg-laoo.ptwl1/HISTORY.md, release/sil/sil.kjg-laoo.ptwl1/source/sil.kjg-laoo.ptwl1.model.kps, release/wyc_eth/wyc_eth.mym-latn.me_en/HISTORY.md, release/wyc_eth/wyc_eth.mym-latn.me_en/source/wyc_eth.mym-latn.me_en.model.kps
Fixes #182 
Now that the lexical-models repo is using 16.0.138 stable of the lexical-model compiler, this PR bumps the version for the listed models in the issue. This forces ES3 code generation to support Android 5.0 devices.
Also updates nrc.str.sencoten
=> chore: Rebuild to use ES3 code generation

sample/example/example.en.custom/source/predict.ts, sample/example/example.en.custom_word_breaker/source/example.en.custom_word_breaker.model.ts
We hadn't exactly maintained the custom model for a while, so this should update it to working order.  I even tested it in KMW by temporarily linking it with one of the testing pages:
The scary thing is... it actually _did_ compile before this, despite some of the referenced types not actually existing.  I went ahead and made sure that all types currently referenced do exist.
=> fix: updates example.en.custom

release/gff/gff.ti_er.gff_tigrinya_eritrea/gff.ti_er.gff_tigrinya_eritrea.kpj, release/gff/gff.ti_et.gff_tigrinya_ethiopia/HISTORY.md, release/gff/gff.ti_et.gff_tigrinya_ethiopia/README.md, release/gff/gff.ti_et.gff_tigrinya_ethiopia/gff.ti_et.gff_tigrinya_ethiopia.kpj, release/gff/gff.ti_et.gff_tigrinya_ethiopia/gff.ti_et.gff_tigrinya_ethiopia.model_info, release/gff/gff.ti_et.gff_tigrinya_ethiopia/source/gff.ti_et.gff_tigrinya_ethiopia.model.kps, release/gff/gff.ti_et.gff_tigrinya_ethiopia/source/readme.htm, release/gff/gff.ti_et.gff_tigrinya_ethiopia/source/welcome.htm
This update fixes some minor but important issues:
* The dictionary display name (&lt;LexicalModel&gt;&lt;Name&gt;) is now populated.
* The `.model_info` file deprecates the region-neutral Tigrinya lexical model.
* `readme.htm` is in synch with the `README.md`
* `welcome.htm` is enhanced.
* Some resource versions (1.2) which were held over from the region-neutral `.kpj` file have been set properly.
Note that the wordlist is unchanged.  The `.kmp` file has been manually installed on an Android phone and verified.
=> GFF Tigrinya-Ethiopia Lexical Model v1.0.1

release/gff/gff.ti_er.gff_tigrinya_eritrea/HISTORY.md, release/gff/gff.ti_er.gff_tigrinya_eritrea/README.md, release/gff/gff.ti_er.gff_tigrinya_eritrea/gff.ti_er.gff_tigrinya_eritrea.kpj, release/gff/gff.ti_er.gff_tigrinya_eritrea/gff.ti_er.gff_tigrinya_eritrea.model_info, release/gff/gff.ti_er.gff_tigrinya_eritrea/source/gff.ti_er.gff_tigrinya_eritrea.model.kps, release/gff/gff.ti_er.gff_tigrinya_eritrea/source/readme.htm, release/gff/gff.ti_er.gff_tigrinya_eritrea/source/welcome.htm
This update fixes some minor but important issues:
* The dictionary display name (&lt;LexicalModel&gt;&lt;Name&gt;) is now populated.
* The `.model_info` file deprecates the region-neutral Tigrinya lexical model.
* `readme.htm` is in synch with the `README.md`
* `welcome.htm` is enhanced.
* Some resource versions (1.2) which were held over from the region-neutral `.kpj` file have been set properly.
* A typo in the `.kpj` that mis-referenced the corresponding `.kps` file, blocking its compilation from the `.kpj` file, has been fixed.
Note that the wordlist is unchanged.  The `.kmp` file has been manually installed on an Android phone and verified.
=> GFF Tigrinya-Eritrea Lexical Model v1.0.1

release/sapradhan/sapradhan.new-newa.nepal_bhasa/HISTORY.md, release/sapradhan/sapradhan.new-newa.nepal_bhasa/LICENSE.md, release/sapradhan/sapradhan.new-newa.nepal_bhasa/README.md, release/sapradhan/sapradhan.new-newa.nepal_bhasa/sapradhan.new-newa.nepal_bhasa.kpj, release/sapradhan/sapradhan.new-newa.nepal_bhasa/source/readme.htm, release/sapradhan/sapradhan.new-newa.nepal_bhasa/source/sapradhan.new-newa.nepal_bhasa.model.kps, release/sapradhan/sapradhan.new-newa.nepal_bhasa/source/welcome.htm
The previous wordlist included 𑐫𑑂 without zwj instead of 𑐫𑑂‌ with zwj. For example, 𑐩𑐫𑑂𑐖𑐸 instead of 𑐩𑐫𑑂‌𑐖𑐸
This has been corrected in the updated wordlist.
=> [sapradhan.new-newa.nepal_bhasa] update wordlist

release/nrc/nrc.en.mtnt/HISTORY.md, release/nrc/nrc.en.mtnt/source/mtnt.tsv, release/nrc/nrc.en.mtnt/source/nrc.en.mtnt.model.kps
Two locations had a space instead of a tab in the .tsv file.
=> [nrc.en.mtnt] fix tabs in lexical model source

package-lock.json, package.json
The @keymanapp/lexical-model-compiler package has unpinned versions for @keymanapp/keyman-version and @keymanapp/models-types. This led to a mismatch in module formats from 16.0 to 17.0. This patch tells npm to use the 16.0.138 version of @keymanapp/keyman-version.
I audited the 17.0 packages and found that they all appear to correctly pin the @keymanapp dependency versions in the deployed packages.
Should unblock #253.
Fixes: keymanapp/keyman#11503
=> fix: pin @keymanapp/keyman-version to 16.0.138

release/cathaylab/cathaylab.nan-latn-035.teochew/cathaylab.nan-latn-035.teochew.model_info
I didn't realize this was also missing. .model_info are still required, will be removed shortly.
=> chore(cathaylab.nan-latn-035.teochew): add also .model_info for teochew

release/burushos/burushos.bsk.burushaski/burushos.bsk.burushaski.model_info
This is needed temporarily until #270 merges (and will need removal again in #271).
=> chore: add .model_info for burushos.bsk.burushaski

sample/example/example.crk.wordlist_wahkohtowin/LICENSE.md, sample/example/example.en.custom/LICENSE.md, sample/example/example.en.custom_word_breaker/LICENSE.md, sample/example/example.en.wordlist/LICENSE.md, sample/example/example.ta.wordlist/LICENSE.md
Follows #271
In preparation for rebuilding all the lexical-models for #246, I noticed sample projects failed to build because they don't contain a LICENSE.md file. (The .kps files already reference the LICENSE.md files)
=> chore: Add LICENSE.md files to sample projects

release/sil/sil.km.ggc/source/sil.km.ggc.model.ts
Fixes https://github.com/keymanapp/keyman/issues/12200.
Recent changes in 18.0-alpha require an update to the custom wordbreaker I originally wrote for this model.  We now seek to model whitespaces in the context to ensure we don't accidentally auto-correct away punctuation marks, but those same changes require precise adherence to the wordbreaker output format.  Unfortunately, my original version of it played a bit... fast and loose, returning improper values for blank or duplicated tokens.
=> fix: fix custom wordbreaker output format for sil.km.gcc

release/sil/sil.jra-khmr.jarai/HISTORY.md, release/sil/sil.jra-khmr.jarai/LICENSE.md, release/sil/sil.jra-khmr.jarai/README.md, release/sil/sil.jra-khmr.jarai/sil.jra-khmr.jarai.kpj, release/sil/sil.jra-khmr.jarai/source/readme.htm, release/sil/sil.jra-khmr.jarai/source/sil.jra-khmr.jarai.model.kps, release/sil/sil.jra-khmr.jarai/source/sil.jra-khmr.jarai.model.ts, release/sil/sil.jra-khmr.jarai/source/welcome.htm
fixes: #235 and #236
With the specified punctuation marks and symbols in the variable, the word from the suggestion bar won't remove them when selected.
=> fix[sil.jra-khmr.jarai] follow the improved script of word prediction

release/chechen_language/chechen_language.ce-latn.chechen/source/chechen_language.ce-latn.chechen.model.kps
The author URL field only supports an email address at this time. No version bump required, this impacts only the compiler, picked up with v18.0 beta compiler
=> chore(chechen_language.ce-latn.chechen): remove https url from email field

ci.sh
parse_args and setup_colors were called but did not exist. This means that ci.sh has been operating as if it has no command line parameters for a long time, and a check of the calls from TeamCity shows that indeed, the script is never passed parameters. Thus, stripped out all the parameterized code paths that would never be called.
Fixes: #317
See-also: #319
=> maint: cleanup ci.sh errors and legacy variables

ci.sh, resources/rsync-tools.inc.sh
Also renames rsync-tools.sh to rsync-tools.inc.sh
Fixes: #326
=> fix: include missing parameter for rsync_to_downloads_keyman_com call
